sudo: false
language: ruby
rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0
services:
  - postgresql
  - redis-server
before_script:
  - psql -c "CREATE DATABASE flippant_test;" -U postgres
addons:
  postgresql: "9.6"
